# -*- coding: utf-8 -*-
"""python read_frames_slow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A9TBVSOQjJSJxa8q900m6DKFSp4cYJ-W
"""

# import the necessary packages

import numpy as np
import argparse
import cv2
# construct the argument parse and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-v", "--video", required=True,
	help="path to input video file")
args = vars(ap.parse_args())
# open a pointer to the video stream and start the FPS timer
print(args)
cap = cv2.VideoCapture(args["video"])

while(cap.isOpened()):
  ret, frame = cap.read()
  #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
  cv2.imshow('frame',frame)
  if cv2.waitKey(30) & 0xFF == ord('q'):
    break

cap.release()
cv2.destroyAllWindows()