name: footprints
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - python=3.6.7
  - pytorch=1.3.1
  - torchvision=0.4.2 # to match pytorch
  - numpy=1.16.3
  - protobuf=3.7.1
  - opencv=3.4.2  # upgraded from 3.3.1 to be compatible with protobuf version needed by TensorFlow
  - pillow=6.2.1
  - pip
  - pip:
    - -r file:requirements.txt
